# a mybinder.org-ready environment for demoing launcher
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate launcher-demo
#
name: launcher-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=2,<3.0.0a0
  # labextension build dependencies
  - nodejs >=14,<15
